interface Color {
  primary: string
  darkBlue: string
  deepBlue: string
  black: string
  white: string
  gray: string
  lightGray: string
  linkBlue: string
  orange: string
  systemWhite: string
  cyan: string
  cyanLight: string
  inactiveDot: string
  divider: string
  todayOffer: string
  yellow: string
  productOffer: string
  green: string
  blue: string
  red: string
  addressBlack: string
  edit: string
  selectedAddress: string
  borderBottom: string
  quantityButton: string
  secondaryGray: string
  stepNumber: string
}

export const COLORS: Color = {
  primary: '#008E97',
  darkBlue: '#041E42',
  deepBlue: '#13274F',
  black: 'black',
  white: '#D0D0D0',
  gray: 'gray',
  lightGray: '#E0E0E0',
  linkBlue: '#007FFF',
  orange: '#FEBE10',
  systemWhite: 'white',
  cyan: '#00CED1',
  cyanLight: '#AFEEEE',
  inactiveDot: '#90A4AE',
  divider: '#D0D0D0',
  todayOffer: '#E31837',
  yellow: '#FFC72C',
  productOffer: '#C60C30',
  green: 'green',
  blue: '#0066B2',
  red: 'red',
  addressBlack: '#181818',
  edit: '#F5F5F5',
  selectedAddress: '#FBCEB1',
  borderBottom: '#F0F0F0',
  quantityButton: '#D8D8D8',
  secondaryGray: '#C0C0C0',
  stepNumber: '#CCC',
}
